port: 7880
bind_addresses:
  - "0.0.0.0"

rtc:
  tcp_port: 7881
  port_range_start: 50100
  port_range_end: 50200
  node_ip: 212.72.24.79
  use_external_ip: false

room:
  auto_create: true

logging:
  level: info

turn:
  enabled: false

keys:
  lamma_dev_key: "80ugLGtb2lpC6E0TgUXuhGP6GKrPirvooNO3cDkD03k="
